- src/extension.ts
- src/remoteConnector.ts
How to test for failure:
- SSH gateway:
- To force the connection to fail we can remove all our ssh keys so you'll be required to use password authentication and then just type an incorrect password
- Local app:
- ....
> Improve ssh analytics

- src/authentication.ts
- src/internalApi.ts
Fixes https://github.com/gitpod-io/gitpod/issues/11296
1. [Run this extension](https://github.com/gitpod-io/gitpod-vscode-desktop/blob/master/docs/CONTRIBUTING.md)
2. Connect to a workspace in any prev env (use SSH gateway) you can use this one https://jp-heartbeat-test.preview.gitpod-dev.com/workspaces
3. After successful connection, delete the gitpod token from database, or you can rebuild the prev env with `with-clean-slate-deployment` so DB gets recreated
4. Try to connect again to a workspace it should ask to login again and not fail silently as before
```release-note
NONE
```
> Fix auth validation

- package.json
- src/common/cache.ts
- src/extension.ts
- src/releaseNotes.ts
- yarn.lock
Fixes #
- Follow steps in https://github.com/gitpod-io/gitpod-vscode-desktop/blob/master/docs/CONTRIBUTING.md
- Press `F5`
- Toggle command `Gitpod: Show Release Note`
```release-note
NONE
```
|Screenshot| Light|
|-|-|
|![image](https://user-images.githubusercontent.com/20944364/178948162-0726d6b3-cebe-41e8-a537-997211d61a46.png)|![image](https://user-images.githubusercontent.com/20944364/178948617-7a1904c7-32b0-450f-8151-bd53813f2e98.png)|
> Add in product changelog

- package.json
- src/releaseNotes.ts
Align to @filiptronicek 's comments https://github.com/gitpod-io/openvscode-server/pull/381#discussion_r925983137
Make release notes shown after vscode startup
> Make release notes shown after vscode startup

- src/remoteConnector.ts
Same as title, to see how many users go with copy password (no SSH public key uploaded yet)
See also [internal chat](https://gitpod.slack.com/archives/C01KGM9BH54/p1658826643857369?thread_ts=1658825096.949629&cid=C01KGM9BH54)
No need
> Add telemetry event for ssh modal

- package.json
- src/common/files.ts
- src/common/platform.ts
- src/remoteConnector.ts
- src/ssh/identityFiles.ts
- src/ssh/sshConfig.ts
- yarn.lock
Support default ssh behaviors of IdentityFile
SSH Config code is a copy of https://github.com/jeanp413/open-remote-ssh/blob/master/src/ssh/sshConfig.ts
Fixes https://github.com/gitpod-io/gitpod/issues/11467
- Follow this doc to run extension locally https://github.com/gitpod-io/gitpod-vscode-desktop/blob/master/docs/CONTRIBUTING.md
- Make sure debug vscode window is actived
- Create a workspace and open with desktop vscode, it should back to the debug window
- Start test with cases below
- Setup your `~/.ssh/config` (mac) with gitpod host and custom identity file
- Add an ssh key to the ssh agent with `ssh-add`
- Run extension with this branch
- Open Gitpod workspace with Desktop VSCode and connect using your debug vscode window
- See if your custom identify file works
- Follow the …
> Get ssh identity file from ssh config and ssh agent

- .github/workflows/nightly.yml
- .github/workflows/release.yml
- package.json
- src/common/logger.ts
- src/experiments.ts
- src/extension.ts
- src/remoteConnector.ts
- yarn.lock
Add experiments using ConfigCat
Fixes https://github.com/gitpod-io/gitpod/issues/12155
```release-note
NONE
```
> Add experiments using ConfigCat

- package.json
- src/extension.ts
- src/remoteConnector.ts
- src/settingsSync.ts
Initialize remote extensions with extensions from sync server
Fixes https://github.com/gitpod-io/gitpod/issues/7906
Related https://github.com/gitpod-io/openvscode-server/pull/419
1. Run this extension and connect to workspace 
2. Install this vsix [gitpod-remote-ssh-0.0.39.zip](https://github.com/gitpod-io/gitpod-vscode-desktop/files/9392713/gitpod-remote-ssh-0.0.39.zip) so it's installed by default the second time
3. Disconnect from workspace
4. Enable settings sync
5. Connect to workspace again and check sync extensions are installed in remote server
> Initialize remote extensions

- src/ssh/sshConfig.ts
If the SSH config on your machine is empty, our extension reads it as just a single newline (`\n`), which made the SSH config parser scream and shout. 
This PR changes the behavior to always trim the SSH config input, so that this single newline becomes an empty string, which is something the library can deal with.
n/a - issue was not reported yet, happened to me at least though. 
1. Download and install this PR's extension build or run with the Remote Extension Host yourself - [gitpod-desktop-0.0.54.vsix.zip](https://github.com/gitpod-io/gitpod-vscode-desktop/files/9452164/gitpod-desktop-0.0.54.vsix.zip)
2. Ensure your settings have `gitpod.remote.useLocalApp` set to `false`
3. Try connecting to a workspace with both some user SSH config and an empty file (`~/.ssh/config`)
> Fix empty SSH config file

- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .gitignore
- .vscodeignore
- docs/releasing.md
- scripts/prepare-nightly-build.js
- scripts/prepare-release-build.js
Ensures (during the automated release process) that release (stable) builds have the correct configuration set and do not use experimental properties only intended for nightly builds at the moment. 
Fixes https://github.com/gitpod-io/gitpod/issues/12476
1. Open a WS with the PR
2. Execute `node scripts/prepare-release-build.js`
3. See the changes that have been made to `package.json`: make sure they changed to values we want for release builds. Those (default) values are:
```json
{
"gitpod.remote.useLocalApp": true
"gitpod.remote.syncExtensions": false
}
```
> Set default config for stable builds during CI

- src/experiments.ts
- src/remoteConnector.ts
Ask for local app fallback when `Timed out while waiting for handshake`
Add `gitpodHost` custom attribute to configcat
Fixes https://github.com/gitpod-io/gitpod/issues/12475
1. Block ssh connections and check a notification is shown, Clicking Ok will fallback to use local-app
To block port 22 you can follow https://www.digitalocean.com/community/tutorials/how-to-set-up-a-firewall-with-ufw-on-ubuntu-18-04 if you are on linux
> Ask for local app fallback when `Timed out while waiting for handshake`

- src/authentication.ts
- src/featureSupport.ts
- src/gitpodServer.ts
- src/remoteConnector.ts
Check for feature support by checking returned session scopes
Related https://github.com/gitpod-io/gitpod/issues/12254
Related PR https://github.com/gitpod-io/gitpod/pull/12446
1. First comment some scope in [related gitpod PR](https://github.com/gitpod-io/gitpod/pull/12446), (I already commented `function:sendHeratbeat`) and build prev env
2. Open workspace in prev env https://jp-oauth-inspect.preview.gitpod-dev.com
3. Connect to workspace from step 2, you'll need to sign in and check heartbeat is disabled in logs
4. Enabled the scope you disabled in step 1 and build prev env
5. Open workspace in prev env https://jp-oauth-inspect.preview.gitpod-dev.com
6. Connect to workspace from step 5, you'll need to sign in again and check heartbeat is enabled in logs
> Support variable scopes

- src/authentication.ts
- src/common/telemetry.ts
- src/experiments.ts
- src/extension.ts
- src/gitpodServer.ts
- src/notification.ts
- src/remoteConnector.ts
- src/settingsSync.ts
This PR normalize analytics events and prepares an experiment for synching local extensions: 
- all events start with `vscode_desktop_` prefix to distinguish from other
- events are instrumented with information about host, user and workspace
- events have `flow` and `status` properties, like `ssh`, `settings-sync`, `sync_local_extensions` flows
- VS Code notifications contribute to flows automatically by instrumenting VS Code APIs
Fixes #
Debug extension, check out analytics in the lab project while connecting via remote ssh and synching local extensions.
```release-note
NONE
```
> flow analytics against vscode apis

- package.json
- scripts/prepare-release-build.js
- src/experiments.ts
- src/remoteConnector.ts
- yarn.lock
Since many users ignore this notification, only 40% of users who noticed it managed to convert, and around 1% of all users never come back if they try to use we decided to quiet this notification on the connection. Instead it logs and we provide an explicit `Install Local Extensions` command to force sync at any time which will prompt a user.
Fixes https://github.com/gitpod-io/gitpod/issues/7906
- Start debugging an extension from this branch.
- Disable Setting Sync with Gitpod.
- Using debug window connect to Gitpod workspace in gitpod.io
- Check that on connection you don't have notifications, but in logs there are error messages that installing local extension failed with a link to enabling Setting Sync with Gitpod.
- Click on the remote indicator and select `Install Local Extensions` …
> quiet installation of local extensions

- src/publicApi.ts
Fixes https://github.com/gitpod-io/gitpod/issues/15292
- Open with this PR and open in Desktop VSCode
- Run `Extension` task (press F5) to start a VSCode process
- Open a workspace with ports defined i.e. https://github.com/mustard-mh/test/tree/hw/logs-ports and open it in started VSCode process
- Check if it works
- Open workspace with gitpod.new and open it in started VSCode process
- Check if it works
> Use binary format

- package.json
- src/common/cache.ts
- src/extension.ts
- src/releaseNotes.ts
This PR contributes a new option, `gitpod.enableReleaseNotes`. This is `true` by default and if turned off, it completely disables the release notes logic for VS Code Desktop.
A hotfix for https://github.com/gitpod-io/gitpod/issues/14533
> Option for disabling release notes

- src/remoteConnector.ts
- src/ssh/sshDestination.ts
Force VS Code to think the server it's connecting to is a Linux host, which caused detection problems on Windows. 
Fixes https://github.com/gitpod-io/gitpod/issues/16058
1. Connect to a workspace with VS Code Desktop (if you can, go get a Windows machine for this)
2. Don't get the OS prompt
> Force Linux host platform for Windows users

- src/common/telemetry.ts
- src/heartbeat.ts
- src/remoteConnector.ts
- src/telemetryReporter.ts
Depends on  https://github.com/gitpod-io/gitpod/pull/16871
> Add error report

- package.json
- src/common/telemetry.ts
- src/metrics.ts
- src/publicApi.ts
- src/telemetryReporter.ts
- yarn.lock
Update connect-node to latest version and analytics-node to the new `@segment/analytics-node` library, old library will be [deprecated soon](https://github.com/segmentio/analytics-next/issues/732#issuecomment-1442558073)
> Update connect-node and analytics-node deps

- package.json
- scripts/prepare-release-build.js
- src/authentication/authentication.ts
- src/configuration.ts
- src/extension.ts
- src/releaseNotes.ts
- src/remoteConnector.ts
- src/remoteSession.ts
- src/services/hostService.ts
- src/services/telemetryService.ts
- src/settingsSync.ts
When activating the extension early with `onResolveRemoteAuthority:ssh-remote`, configuration default values are not available yet and will return `undefined` so we hardcode the defaults
- Ensure you don't have changed any gitpod configuration in your settings.json if so then remove it first, so default values are used
- Try connecting to a workspace in gitpod.io as this is the default value, connection should be successful and the extension is activated
> Readd `onResolveRemoteAuthority:ssh-remote` and fix for configuration default values

- src/extension.ts
- src/local-ssh/ipc/extension.ts
Only show workspace stopping notification if window is correct remote window
This will fixes IDE-58
Fixes #
1. open workspace in vscode desktop
2. stop workspace
3. try to reconnect 
4. the notification `workspace is not running, current phase ...` should always show in correct remote window.
> Only show workspace stopping notification if window is correct remote window

- src/local-ssh/ipc/extension.ts
- src/local-ssh/ipc/localssh.ts
- src/local-ssh/server.ts
- src/local-ssh/sshTunnel.ts
- src/proto/ipc/v1/ipc.proto
- src/proto/typescript/ipc/v1/ipc.ts
Remove the deprecated `failureReason` field
Fixes #
1. start a workspace
2. trying to open this workspace in desktop
3. during this time quickly do `rm -rf ~/.ssh/authorized_keys` a few times, you can use `while`, it will cause tunnel ssh auth failed.
4. check `ide-metrics` logs
> Remove deprecated failureReason field and add error report

- package.json
- src/experiments.ts
- src/extension.ts
Make the URL host of the experiments client configurable with the good ol' `gitpod.host`.
Fixes [IDE-75](https://linear.app/gitpod/issue/IDE-75/[code-desktop]-align-usage-of-configcat-for-dedicated)
> Dynamic experiments host

- .github/workflows/nightly.yml
Creates a convention where `master` gets synced every night to the `pre` branch, from which a new (nightly) version of the extension is published, inspired by [GitLens](https://github.com/gitkraken/vscode-gitlens). 
Succeeds https://github.com/gitpod-io/gitpod-vscode-desktop/pull/40
https://gitpod.slack.com/archives/C045J13P8A1/p1684171765423839
Run the workflow from https://github.com/gitpod-io/gitpod-vscode-desktop/tree/ft/nightly-prereleases. The `pre` branch should update with any `master` changes and if there none, the workflow should not continue.
> Pre-release branch, `pre`

- src/services/telemetryService.ts
- Package extension locally with `yarn package` and you can throw exception somewhere using `telemetryException`
- Install extension locally
- See if there are logs about it with prefix `Local error report`
> Disable error report if extension is not packaged by GHA IDE-108

- src/ssh/sshConfig.ts
Relates [IDE-165](https://linear.app/gitpod/issue/IDE-165)
✅  See https://github.com/gitpod-io/gitpod-vscode-desktop/pull/79#issuecomment-1590682496
1️⃣  It can replace old content
- Have previsous setup or use previous extension version
- Package and install PR version
- open workspace, and check `~/.ssh/config`(use code_gitpod.d), `~/.ssh/code_gitpod.d/config`(create), `~/.ssh/gitpod/config` (deleted)
2️⃣  It can add new content
3️⃣  It should replace old content and don't delete `~/.ssh/gitpod` folder if it contains another file
4️⃣  It should not delete `~/.ssh/gitpod/config` if it's not generated by us
/hold
> Change gitpod config location IDE-165

- src/commands/workspaces.ts
- src/common/metrics.ts
- src/experiments.ts
- src/extension.ts
- src/publicApi.ts
- src/remoteSession.ts
- src/services/localSSHMetrics.ts
- src/services/remoteService.ts
- src/workspaceState.ts
- src/workspacesExplorerView.ts
Support ssh gateway when connecting from workspace explorer
1. Disable local ssh in configcat
2. Connect using workspace explorer, it should work
> Support ssh gateway when connecting from workspace explorer

- src/common/telemetry.ts
- src/local-ssh/proxy.ts
- src/local-ssh/telemetryService.ts
- add started/exited status reporting to identify hanging process
- don't swallow errors, but report all, we can sort them out later to investigate root causes of hanging
- add detection of stale web sockets to prevent hanging similar how it is done by Local App
Fixes #
/hold
> [local ssh] improve observability and try to prevent hanging

- package.json
- src/publicApi.ts
- yarn.lock
https://github.com/bufbuild/connect-es/pull/712 got merged and also added unit tests, let's update and see if we can remove the workaround after this is merged and deployed
> Upgrade connect lib

- src/local-ssh/proxy.ts
electron seems remove support for `--ms-enable-electron-run-as-node` flags in `vscode insider` It will cause electron not to swallow this flags, resulting in a change in our parameter position.
Fixes #
1. build a extension using this branch and install it in both `vscode insider` and `vscode stable`, and restart vscode
2. try to open workspace via `vscode insider` and `vscode stable`
3. check remote hostname, it should be `*.vsi.*` or `*.vss.*`
/hold
> Fix local-ssh not work in vscode insider

- src/extension.ts
- src/remoteConnector.ts
- src/services/hostService.ts
Fixes [ENT-181](https://linear.app/gitpod/issue/ENT-181)
- Build and use extension
- It should update settings remotePlatform to `linux` when connecting to a workspace in Gitpod
- It should be able to connect to workspaces
/hold
> Always update remotePlatform for gitpodHost's wildcard

- src/experiments.ts
- src/extension.ts
- src/remoteConnector.ts
- src/remoteSession.ts
Fixes [[internal doc](https://www.notion.so/gitpod/gitpod_experimental_publicApi-659625069fce443c8b65848b1e1d5e5b?pvs=4)], ENT-295
It can open and connect workspaces in Gitpod
|Local SSH|SSH Gateway|
|:-:|:-:|
|<img width="1287" alt="image" src="https://github.com/gitpod-io/gitpod-vscode-desktop/assets/20944364/dccb296e-97ea-4dba-b016-10c2ed46cae4">|<img width="1253" alt="image" src="https://github.com/gitpod-io/gitpod-vscode-desktop/assets/20944364/be74a917-bad9-437d-8341-337765a20ec4">|
/hold
> Always use public API

- package.json
- src/commands/logs.ts
- src/commands/workspaces.ts
- src/remoteConnector.ts
Collect lssh logs in connection window
/hold
> Collect lssh logs in connection window

- package.json
- src/heartbeat.ts
Official description of `active` property
> Whether the window has been interacted with recently. This will change immediately on activity, or after a short time of user inactivity.
Fixes [[internal chat](https://gitpod.slack.com/archives/C0201TXMV54/p1720603695491779?thread_ts=1720593853.632269&cid=C0201TXMV54)]
No need?
/hold
> Improve heartbeat activity detection on `onDidChangeWindowState` event

- package.json
- src/extension.ts
Use modal dialog when in gitpod flex env
Fixes https://linear.app/gitpod/issue/NEXT-1595/cannot-open-gitpod-workspace-from-flex-environment-window
/hold
> Use modal dialog when in gitpod flex env

- src/commands/workspaces.ts
- src/remote.ts
- src/remoteConnector.ts
- src/services/remoteService.ts
If a user happens to use the "Reopen in container" feature of VS Code Desktop, we should still be able to send heartbeats and not let workspaces time out.
1. Build the extension using `yarn package`
2. Install it 
3. Open a workspace from https://github.com/filiptronicek/vscode-remote-try-go/tree/ft/ak/magic in `catfood`
4. Use "Reopen in Container" when VS Code Desktop asks you
5. Check the Gitpod output to see we're sending heartbeats every now and then
> Dev Container heartbeats

- package.json
- src/services/remoteService.ts
Only write dev.containers.defaultExtensions setting if devcontainers extension is installed
Fixes #
/hold
> Only write dev.containers.defaultExtensions setting if devcontainers extension is installed

- package.json
- src/services/hostService.ts
Add view with Gitpod Flex instructions
Fixes https://linear.app/gitpod/issue/NEXT-2305/[vscode]-add-new-webview-in-classic-with-gitpod-flex-instructions
/hold
> Add view with Gitpod Flex instructions

- package.json
- src/publicApi.ts
Don't use binary format, binary format forces http2, it's preferable to downgrade to http1.1 if http2 is not available for some reason 
Fixes #
/hold
> Don't use binary format for transport in public api client
