gitpod-io/gitpod-vscode-desktop

- src/extension.ts
- src/remoteConnector.ts
Continuation from #2, fixes broken analytics when using local-app
> Improve ssh analytics 2

- src/releaseNotes.ts
Fixes #
- Run with extension
- Toggle command to show release notes
- See if the header image works
> Fix related image path not shown in changelog

- src/featureSupport.ts
- src/remoteConnector.ts
Fixes #
Change gitpod host to incorrect one, see if it failed with version `0.0.0`
> Use min version once version api unreachable

- .mocharc.json
- package.json
- src/featureSupport.test.ts
- tsconfig.json
- yarn.lock
> Add unit test for featureSupport.ts

- .github/workflows/pr.yml
Adds a GitHub Action workflow to build and package the extension for simple CI.
As it goes with GH Actions, other than code review, merge and see 😆.
> Add PR CI workflow

- src/remoteConnector.ts
Removes this:
because of [this](https://gitpod.slack.com/archives/C045J13P8A1/p1669719254002629) (Slack message)
> Remove installing extensions notification

- package.json
- src/metrics.ts
- src/publicApi.ts
- yarn.lock
> Add grpc metrics

- package.json
- src/publicApi.ts
- src/remoteConnector.ts
- src/workspaceState.ts
Reverts commits:
- 67977bba0881407b3c0c94a2cc08546df1961bae
- 80e61626d3258204dca8f75efd4682d7d1861356
- 12940df6d1c50b0460e8071867684d1f256f8679
- 42ecf1faba8c0f90f8db6b3dafbbab7a8e378b7d
> Revert last changes from yesterday

- src/remoteConnector.ts
- Add phase for NoRunningInstanceError
> Add retry to avoid network problem

- .github/workflows/nightly.yml
- .github/workflows/release.yml
- src/authentication/authentication.ts
- src/commands/logs.ts
- src/common/telemetry.ts
- src/daemonStarter.ts
- src/extension.ts
- src/heartbeat.ts
- src/local-ssh/ipc/extension.ts
- src/local-ssh/ipc/localssh.ts
- src/local-ssh/server.ts
- src/local-ssh/sshTunnel.ts
- src/proto/ipc/v1/ipc.proto
- src/proto/typescript/ipc/v1/ipc.ts
- src/remote.ts
- src/remoteSession.ts
- src/services/telemetryService.ts
- src/settingsSync.ts
depends on https://github.com/gitpod-io/gitpod/pull/17162
Fixes #
```release-note
```
> report telemetry to corresponding host

- src/heartbeat.ts
Related https://linear.app/gitpod/issue/IDE-18/align-ssh-events-for-all-clients
> Add `ide_heartbeat` telemetry IDE-19

- src/daemonStarter.ts
- src/local-ssh/ipc/localssh.ts
- src/local-ssh/logger.ts
- src/local-ssh/server.ts
Same with title
Related https://linear.app/gitpod/issue/IDE-50
- Install extension locally
- Connect to any workspaces
- Exec `gp stop` to stop workspace
- It should close connection to local-ssh daemon
|SSH Gateway| Local SSH |
|:-:|:-:|
|![SCR-20230426-vi0](https://user-images.githubusercontent.com/20944364/234620592-a8e5049e-8d6b-493b-b0f1-70e422615f04.png)|![SCR-20230426-w5l](https://user-images.githubusercontent.com/20944364/234620639-8a7b27ee-2d08-4e39-b70f-259d2faf92e8.png)|
> Close conn based on piped conn IDE-50

- src/local-ssh/common.ts
- src/local-ssh/server.ts
- src/local-ssh/sshTunnel.ts
- src/remoteConnector.ts
Fixes https://linear.app/gitpod/issue/IDE-52
- Check progress notification shows
- Check dns lookup timeout after 10s
> Add timeout to dns lookup and progress notification

- src/extension.ts
- src/local-ssh/ipc/extensionServiceServer.ts
- src/local-ssh/proxy.ts
- src/proto/ipc/v1/ipc.proto
- src/proto/typescript/ipc/v1/ipc.ts
- src/remote.ts
- src/remoteConnector.ts
- src/services/localSSHService.ts
> Proper analytics and error reporting IDE-77

- src/local-ssh/ipc/extensionServiceServer.ts
- src/proto/ipc/v1/ipc.proto
- src/proto/typescript/ipc/v1/ipc.ts
- src/remoteConnector.ts
- src/services/localSSHService.ts
Relates [IDE-77](https://linear.app/gitpod/issue/IDE-77)
/hold
> Ping extension ipc server before use local ssh IDE-77

- src/remoteConnector.ts
> separate local ssh and gateway (ssh flow)

- src/authentication/authentication.ts
- src/internalApi.ts
- src/publicApi.ts
Fixes [IDE-162](https://linear.app/gitpod/issue/IDE-162)
✅ https://github.com/gitpod-io/gitpod-vscode-desktop/pull/80#issuecomment-1592464464
Add break points and test with cases below
- Server API with random workspaceID
- Server API without auth token
- Public API with random workspaceID
- Public API without auth token
/hold
> Proper category errors from serverApi and publicApi IDE-162

- src/heartbeat.ts
to prevent resource exhausted errors
Fixes #
/hold
> double heartbeat interval

- src/common/utils.ts
- src/local-ssh/ipc/extensionServiceServer.ts
- src/local-ssh/proxy.ts
- src/publicApi.ts
I'm not sure how to reproduce an error condition. With network limitter on bad network nothing is logged only everything is hanging. I assume we can test that happy path working, then release and see what kind of errors are propagating to us.
Fixes #
/hold
> report getWorkspaceAuthInfo error to GCP

- package.json
- src/publicApi.ts
- yarn.lock
Connect changes https://github.com/mustard-mh/connect-es/commit/1922b79f84cfe230c6b01e3f5c4f13f7b43b9f74
Fixes #
It should not break anything
/hold
> Use custom connect-node lib

- src/local-ssh/ipc/extensionServiceServer.ts
- src/local-ssh/proxy.ts
Try to convert ServiceError into readable error code
Fixes https://gitpod.slack.com/archives/C045J13P8A1/p1689083942010629?thread_ts=1688971512.520299&cid=C045J13P8A1
/hold
> Process errors from supervisor grpc-web lib

- src/local-ssh/ipc/extensionServiceServer.ts
- src/local-ssh/proxy.ts
Fixes [internal-chat](https://gitpod.slack.com/archives/C045J13P8A1/p1689150936567299?thread_ts=1688971512.520299&cid=C045J13P8A1)
It can connect via local-ssh
/hold
> Wrap supervisor api with error and retry

- src/local-ssh/ipc/extensionServiceServer.ts
We don't handle properly context or IDE URLs generally and it is causing burn of local SSH in particularly. This PR addresses only this issue. For general proper handling I will create a separate issue for @jeanp413 
Fixes #
/hold
> local ssh: fix invalid URL

- package.json
- src/local-ssh/proxy.ts
- yarn.lock
Avoid stale disconnects when network is slow
Fixes https://github.com/gitpod-io/gitpod/issues/19284
/hold
> Avoid stale disconnects when network is slow

- package.json
- src/extension.ts
- src/remote.ts
Fix and rename inGitpodFlexRemoteWindow context key
Fixes #
/hold
> Fix and rename inGitpodFlexRemoteWindow context key

- package.json
- src/extension.ts
Show message when extension disabled in gitpod flex environment
Fixes https://linear.app/gitpod/issue/NEXT-1595
/hold
> Show message when extension disabled in gitpod flex environment

- .github/workflows/nightly.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
Use node 20 in gh workflows
/hold
> Use node 20 in gh workflows

- README.md
- package.json
Fixes https://gitpod.slack.com/archives/C06C23ZTFL6/p1731333386534599?thread_ts=1730981493.776589&cid=C06C23ZTFL6
> `Gitpod` → `Gitpod Classic`
